/**
 * This file documents the TypeScript types generated by Prisma
 * These are automatically generated in node_modules/@prisma/client
 * 
 * This is for reference only - the actual types are in @prisma/client
 */

// ==============================================================================
// GENERATED TYPES (auto-generated by Prisma - DO NOT EDIT MANUALLY)
// ==============================================================================

/**
 * Tenant type - represents a row in the tenants table
 */
export type Tenant = {
  id: string;
  name: string;
  description: string | null;
  createdAt: Date;
};

/**
 * User type - represents a row in the users table
 */
export type User = {
  id: string;
  email: string;
  password: string;
  isAdmin: boolean;
  tenantId: string;
  createdAt: Date;
};

/**
 * Camera type - represents a row in the cameras table
 */
export type Camera = {
  id: string;
  tenantId: string;
  frigateCameraKey: string;
  label: string | null;
  isEnabled: boolean;
  createdAt: Date;
};

/**
 * Event type - represents a row in the events table
 */
export type Event = {
  id: string;
  tenantId: string;
  cameraId: string;
  frigateId: string;
  type: string;
  label: string | null;
  hasSnapshot: boolean;
  hasClip: boolean;
  startTime: number | null;
  endTime: number | null;
  rawPayload: Record<string, unknown>;
  createdAt: Date;
};

/**
 * Review type - represents a row in the reviews table
 */
export type Review = {
  id: string;
  tenantId: string;
  cameraId: string;
  reviewId: string;
  cameraName: string;
  severity: string;
  retracted: boolean;
  timestamp: Date | null;
  rawPayload: Record<string, unknown>;
  createdAt: Date;
};

/**
 * AvailabilityLog type - represents a row in the availability_logs table
 */
export type AvailabilityLog = {
  id: string;
  tenantId: string;
  available: boolean;
  timestamp: Date;
  rawPayload: Record<string, unknown>;
  createdAt: Date;
};

// ==============================================================================
// EXTENDED TYPES WITH RELATIONS
// ==============================================================================

/**
 * Tenant with all relations
 */
export type TenantWithRelations = Tenant & {
  users: User[];
  cameras: Camera[];
  events: Event[];
  reviews: Review[];
  availabilityLogs: AvailabilityLog[];
};

/**
 * Camera with all relations
 */
export type CameraWithRelations = Camera & {
  tenant: Tenant;
  events: Event[];
  reviews: Review[];
};

/**
 * Event with all relations
 */
export type EventWithRelations = Event & {
  tenant: Tenant;
  camera: Camera;
};

/**
 * Review with all relations
 */
export type ReviewWithRelations = Review & {
  tenant: Tenant;
  camera: Camera;
};

/**
 * AvailabilityLog with all relations
 */
export type AvailabilityLogWithRelations = AvailabilityLog & {
  tenant: Tenant;
};

// ==============================================================================
// USAGE EXAMPLES
// ==============================================================================

/**
 * @example
 * import type { Event, Camera, Tenant } from '@prisma/client';
 * import { prisma } from './src/db/client';
 *
 * // Query with types automatically inferred
 * const event: Event = await prisma.event.findUniqueOrThrow({
 *   where: { id: 'event-123' }
 * });
 *
 * // Include relations
 * const eventWithTenant = await prisma.event.findUnique({
 *   where: { id: 'event-123' },
 *   include: { tenant: true, camera: true }
 * });
 * // type is automatically EventWithRelations
 *
 * // Create with auto-completed fields
 * const newEvent = await prisma.event.create({
 *   data: {
 *     tenantId: 'tenant-1',
 *     cameraId: 'camera-1',
 *     frigateId: 'frigate-event-123',
 *     type: 'person',
 *     rawPayload: {},
 *     // label, hasSnapshot, hasClip, startTime, endTime are optional
 *   }
 * });
 */

// ==============================================================================
// HOW TO USE THESE TYPES
// ==============================================================================

/**
 * Import types in your files:
 *
 * import type { Tenant, Camera, Event } from '@prisma/client';
 * import { prisma } from './db/client';
 *
 * async function processEvent(event: Event) {
 *   // event is fully typed
 *   console.log(event.frigateId, event.type);
 * }
 */

// ==============================================================================
// TYPE GENERATION
// ==============================================================================

/**
 * These types are automatically generated by Prisma from the schema.
 *
 * To regenerate after schema changes:
 * $ npm run prisma:generate
 *
 * Or Prisma will auto-generate on migration:
 * $ npm run prisma:migrate
 */

// ==============================================================================
// INTELLISENSE FEATURES
// ==============================================================================

/**
 * When using TypeScript with Prisma:
 *
 * 1. Full autocomplete for all fields on models
 * 2. Type-safe relation navigation
 * 3. Compile-time errors for typos
 * 4. Auto-inferred return types from queries
 * 5. Smart filtering and selection hints
 *
 * Example:
 * const events = await prisma.event.findMany({
 *   where: {
 *     type: 'person',  // autocomplete suggests valid types
 *     tenantId: '...'
 *   },
 *   select: {
 *     id: true,        // autocomplete shows all available fields
 *     type: true,
 *     camera: {        // autocomplete for relations
 *       select: { label: true }
 *     }
 *   }
 * });
 * // Return type is automatically inferred as correct shape
 */
